### ISSUE TITLE
API for core data /event/device/{deviceId}/{limit}: does not work with deviceId but deviceName

### ISSUE THREAD

**Issue by otmezger** [edgexfoundry/core-data#6]
I've found another documentation issue with the `core-data.raml`: It reads `/event/device/{deviceId}/{limit}: ` but actually should be `/event/device/{deviceName}/{limit}: ` as it works ONLY with `deviceName` and NOT with `deviceID`.

As mentioned to @jpwhitemn in rocket chat: https://chat.edgexfoundry.org/channel/general?msg=QP33tpNs5YCqkA5xh

**Comment by jpwhitemn** [comment]
The API and documentation are correct.  The API allows for the device name or the device id to be used to get the data for the Event collection - whichever is used by the device service to report the event/reading.  In other words, one or the other can be used, but not both.  In the case of the virtual device service, it reports its reading via the device name.  Therefore the event/readings are available via core data by the event name.  Since Core Data does not have information about both the name and id, it uses what is provided in the event/reading to filter the data.  A future version of the service may want to implement a query first to Metadata on the id or name provided through the request and determine which to use to query the database.
